### PR TITLE
Removed recast dep, added dep on newest ast-types

### PR DESCRIPTION
**Pull request by ethancrook99**

### CODE REVIEW

**Review by jimmyandrade — APPROVED** [review]
LGTM

**Review by shilman — CHANGES_REQUESTED** [review]
@ethancrook99 thanks for this--looking good! can you add a simple test case with optional chaining to show that it's working?

**Comment by ethancrook99** [comment]
@shilman No problem! I added a test case called optionalChaining, let me know if it works well enough/covers the changes properly. I also added @babel/plugin-proposal-optional-chaining to `.babelrc` and to the test config plugins so everything works together nicely.

**Comment by idbartosz** [comment]
@ethancrook99 thanks for taking care of this 👍 

Looking at the output of `optionalChaining/output.js` I'd say that you're not covering the the use cases. You need to add some props to actually check if the `App.__docgenInfo` has the expected data. You could also remove unnecessary boilerplate from the fixture and only leave the essential optional chaining and propos (see [HOC fixture](https://github.com/storybookjs/babel-plugin-react-docgen/blob/master/test/fixtures/hoc))

**Comment by ethancrook99** [comment]
@idbartosz I updated the test, can you take a look at it?

**Comment by idbartosz** [comment]
LGTM 👍 

CC @shilman

**Review by shilman — APPROVED** [review]
Thanks for your patience on this! Merging and will release shortly 🙏

**Pull request merged**
