### PR TITLE
V5 with jest snapshots

### PR DESCRIPTION
**Pull request by shilman**
## What I did

The snapshots were all broken in the other branch, so I:
- [x] Upgraded to v5
- [x] Upgraded to jest snapshotting
- [x] Cleaned up the snapshot tests a bit
- [x] Upgraded to yarn

This more closely matches the tooling in rest of the `@storybook/*` repos, but feel free to reject if it doesn't suit your tastes.

## What I need

Did not actually review the snapshots yet. Can you take a look?

### CODE REVIEW

**Comment by danielduan** [comment]
Also, looks like `5.0.0` has been published, so feel free to bump the version and publish as well!

**Comment by shilman** [comment]
@danielduan Thanks! Bumped package versions, but don't have publish access on `npm`. Can you add me?

**Comment by danielduan** [comment]
Invited! :)

**Comment by shilman** [comment]
Thanks @danielduan. I released `beta.3` and will wait for @patricklafrance to test the heck out of it before merging & releasing a new major.

**Comment by patricklafrance** [comment]
@shilman all the tests still fail because of the paths, do I have to do something?

In your commit https://github.com/storybookjs/babel-plugin-react-docgen/pull/80/commits/d5125630cd0183df936c47e280ae950b238d80d3 you dont seem to have updated the snapshots? Only updated the code to use relativePath, maybe this is the issue?

**Pull request merged**
