### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by stof**
This avoids referencing vulnerable versions in the lock file:

- solved 2 github alerts
- `npm audit` goes from 227 vulnerabilities to 0.

### CODE REVIEW

**Comment by stof** [comment]
The build error is because CircleCI is not configured in this repo (there is a Travis configuration). I don't know why it tries to run.

**Comment by danielduan** [comment]
thank you for the help in upgrading, let me manually test this before merging. i suspect the diffs in the tests are just from dependency upgrades but i want to double check that.

**Comment by stof** [comment]
@danielduan yes, this is the update of the babel helper, specifically https://github.com/babel/babel/commit/9ec26a7d3ee2dceff75d2872721ff23e3dd83df3

A solution to limit the diff for future updates of babel could be to configure the testsuite to import helpers from the `@babel/runtime` package instead of copying them in the transpiled output. This way, fixtures would not change when the internal implementation of helpers changes.

**Comment by danielduan** [comment]
published as `3.2.0`

**Pull request merged**
